name: payflow
description: NLW TOGETHER

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  google_fonts: ^2.2.0
  firebase_core: ^1.11.0
  google_sign_in: ^5.2.3
  google_sign_in_web: ^0.10.0+4
  shared_preferences: ^2.0.12
  google_ml_kit: ^0.7.3
  camera: ^0.9.4+7
  image_picker: ^0.8.4+5
  font_awesome_flutter: ^9.2.0
  flutter_masked_text2: ^0.9.1
  animated_card: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
